version: '3'
services:
  apisrv:
    build: .
    environment:
      - redis_url=redis://redis
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    healthcheck:
      test: ["CMD", "curl -f localhost:9090/status && echo 'ready'"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
