version: '3'
services:
  apisrv:
    build: .
    environment:
      - redis_url=redis://redis
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine"
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
